[package]
name = "eva-alloc"
version = "0.1.0"
edition = "2024"
authors = ["Davide Mor <tazdevil971@gmail.com>"]

[dependencies]
linked_list_allocator = { version = "0.10", default-features = false }
critical-section = "1.0.0"