[package]
name = "eva-bsp-stm32f767"
version = "0.1.0"
edition = "2024"
authors = ["Davide Mor <tazdevil971@gmail.com>"]

[dependencies]
eva-pac = { workspace = true }
eva-alloc = { workspace = true }
eva-scheduler = { workspace = true }

rtt-target = { workspace = true }