[env]
EVA_TARGET_CHIP = "stm32f767zi"
CROSS_COMPILE = "arm-none-eabi"

[build]
target = "../thumbv7em-eva-eabihf.json"

[target.thumbv7em-eva-eabihf]
runner = "probe-rs run --chip STM32F767ZITx"

[profile.releaseplus]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1

[unstable]
build-std = ["core", "alloc", "std", "panic_abort"]
# build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true 