[build]
target = "../x86_64-evalinux-gnu.json"

[profile.size]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
strip = true

[unstable]
build-std = ["core", "alloc", "std", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]