[package]
name = "eva-scheduler"
version = "0.1.0"
edition = "2024"
authors = ["Davide Mor <tazdevil971@gmail.com>"]

[dependencies]
lock_api = "0.4"
rtt-target = { workspace = true }
critical-section = { workspace = true, features = ["restore-state-bool"] }