[package]
name = "eva-bsp-linux"
version = "0.1.0"
edition = "2024"
authors = ["Davide Mor <tazdevil971@gmail.com>"]

[dependencies]
eva-alloc = { workspace = true }
eva-scheduler = { workspace = true }

libc = { version = "0.2", default-features = false }