[env]
EVA_TARGET_CHIP = "stm32f767zi"
CROSS_COMPILE = "arm-none-eabi"

[build]
target = "./thumbv7em-eva-eabihf.json"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true 